### ISSUE TITLE
Unable to detect valid initrd

### ISSUE THREAD

**Issue by ryan-codingintrigue** [dell/dell-recovery#79] opened 2019-05-10 07:55 UTC
**Machine:**
Dell XPS 13 9380 - Ubuntu 18.04 (Preinstalled)

**Steps:**
1. Select Base OS Image: *ubuntu-19.04-desktop-amd64.iso*
2. Select FID Content:
   - Choose package
   - Build dell-recovery package from this system
3. Leave Driver Packages as default
4. Leave Application Packages as default
5. Media Type: No media, create image
6. Confirm Selections
7. Apply

I've tried this with different images, all vanilla images downloaded direct from Ubuntu and I get the same error on each.

I mounted the ISO and confirmed that these paths exist:
```
/path/to/iso/casper/initrd
/path/to/iso/.disk/casper-uuid-generic
```

**Comment by superm1** [comment] 2019-05-10 16:58
It sounds like 19.04 might have dropped the extension of the initrd.  I can reproduce the same thing with a 19.04 image.

**Comment by ryan-codingintrigue** [comment] 2019-05-10 16:59
I did try with an 18.04 XUbuntu ISO and had the same result...not sure if that helps

**Comment by superm1** [comment] 2019-05-10 17:00
Well I see the same thing with 18.04.x images too.  So it was probably a build script change to stop using the suffix `.lz` or `.gz` and when the images spun for the last point release the same thing happened to all those.

**Comment by superm1** [comment] 2019-05-10 17:01
To confirm that - I have a 18.04.1 image `ubuntu-18.04.1-desktop-amd64.iso` on my desktop and it's
`/casper/initrd.lz`

**Comment by superm1** [comment] 2019-05-10 18:04
It's not just a matter of the suffix being wrong, it's really actually uncompressed and jammed together with microcode now.

The basic symptoms described here happen to it:
https://serverfault.com/questions/876140/cpio-incorrectly-unpacking-initrd-in-ubuntu-xenial

**Comment by superm1** [comment] 2019-05-10 18:06
My best guess would be that this was because of spectre/meltdown and needing to get the microcode update loaded super early.

**Comment by superm1** [comment] 2019-05-10 18:14
Alright so due to the initramfs format this is going to require a little bit of surgery in the initramfs generation for dell-recovery.

Here is a sample of the new format:
```
.:
early
early2
main

./early:
kernel

./early/kernel:
x86

./early/kernel/x86:
microcode

./early/kernel/x86/microcode:
AuthenticAMD.bin

./early2:
kernel

./early2/kernel:
x86

./early2/kernel/x86:
microcode

./early2/kernel/x86/microcode:
GenuineIntel.bin

./main:
bin
conf
cryptroot
etc
init
lib
lib64
run
sbin
scripts
usr
var
```

Changes needed:
1. Don't fail on empty old suffix
2. Don't fail if empty new suffix
3. Decompress using `unmkinitramfs` and recompress using `mkinitramfs`

If you want to get your hands dirty, happy to review patches for this.

**Comment by ryan-codingintrigue** [comment] 2019-05-10 18:41
I can give this a go, sure! Python isn’t my go-to language but it seems a straightforward enough change.

**Comment by superm1** [comment] 2019-05-10 18:43
Awesome, thanks!  I think you can probably tear out alot of that custom cpio stuff and extension detection when switching to `unmkinitramfs`/`mkinitramfs`.  I think that those tools will handle the extensions under the covers for you then.

A good reference test is to try it with a new ubuntu image as well as your factory shipped image on the 9380 (so it tests both approaches).

**Comment by superm1** [comment] 2019-06-20 21:12
To anyone following along the work for this was started here: https://github.com/ryan-codingintrigue/dell-recovery/commit/0aa9db32226e2b19005d4eb8aa4354cf91d9e75d.  It hasn't had a PR back into dell-recovery yet.

**Comment by superm1** [comment] 2019-10-03 04:44
Fixed in master

**Closed by superm1** 2019-10-03 04:44 UTC
Labels: bug, enhancement, help wanted
